# Ключ для модели Gemini
GEMINI_API_KEY = "AIzaSyAdRIkziGDw4NB-WEwvpWIpLCPn91fb8JQ"
# Ключ для Google Поиска
GOOGLE_API_KEY = "AIzaSyBT-4rybFh2z5JA9c7x7bsPo1Te61TKnxY"
# ID вашей поисковой системы
PSE_ID = "80a6594642720429b"